//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDImportKunden.DB100
{

    public partial class KUND1 : XPLiteObject
    {
        string fLiAnrede;
        [Size(10)]
        public string LiAnrede
        {
            get { return fLiAnrede; }
            set { SetPropertyValue<string>(nameof(LiAnrede), ref fLiAnrede, value); }
        }
        string fLiName;
        [Size(50)]
        public string LiName
        {
            get { return fLiName; }
            set { SetPropertyValue<string>(nameof(LiName), ref fLiName, value); }
        }
        string fLiVorname;
        [Size(50)]
        public string LiVorname
        {
            get { return fLiVorname; }
            set { SetPropertyValue<string>(nameof(LiVorname), ref fLiVorname, value); }
        }
        string fLiName2;
        public string LiName2
        {
            get { return fLiName2; }
            set { SetPropertyValue<string>(nameof(LiName2), ref fLiName2, value); }
        }
        string fLiStrasse;
        [Size(50)]
        public string LiStrasse
        {
            get { return fLiStrasse; }
            set { SetPropertyValue<string>(nameof(LiStrasse), ref fLiStrasse, value); }
        }
        string fLiPlz;
        [Size(15)]
        public string LiPlz
        {
            get { return fLiPlz; }
            set { SetPropertyValue<string>(nameof(LiPlz), ref fLiPlz, value); }
        }
        string fLiOrt;
        [Size(50)]
        public string LiOrt
        {
            get { return fLiOrt; }
            set { SetPropertyValue<string>(nameof(LiOrt), ref fLiOrt, value); }
        }
        string fLiLand;
        [Size(50)]
        public string LiLand
        {
            get { return fLiLand; }
            set { SetPropertyValue<string>(nameof(LiLand), ref fLiLand, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("Nr")]
            public decimal Nr { get; set; }
            [Size(15)]
            [Persistent("Kunde")]
            public string Kunde { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
