//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDDatenbankLibraryCRM.Database
{

    public partial class BDDatenbankTabelle : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fDatenbank;
        public string Datenbank
        {
            get { return fDatenbank; }
            set { SetPropertyValue<string>(nameof(Datenbank), ref fDatenbank, value); }
        }
        string fTabelle;
        public string Tabelle
        {
            get { return fTabelle; }
            set { SetPropertyValue<string>(nameof(Tabelle), ref fTabelle, value); }
        }
        string fBeschreibung;
        [Size(1000)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>(nameof(Beschreibung), ref fBeschreibung, value); }
        }
        [Association(@"BDDatenbankTabelleFeldReferencesBDDatenbankTabelle")]
        public XPCollection<BDDatenbankTabelleFeld> BDDatenbankTabelleFelds { get { return GetCollection<BDDatenbankTabelleFeld>(nameof(BDDatenbankTabelleFelds)); } }
    }

}
