//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDDatenbankLibraryCRM.Database
{

    public partial class BDDatenbankTabelleFeld : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        BDDatenbankTabelle fTabelle;
        [Association(@"BDDatenbankTabelleFeldReferencesBDDatenbankTabelle")]
        public BDDatenbankTabelle Tabelle
        {
            get { return fTabelle; }
            set { SetPropertyValue<BDDatenbankTabelle>(nameof(Tabelle), ref fTabelle, value); }
        }
        string fFeldname;
        public string Feldname
        {
            get { return fFeldname; }
            set { SetPropertyValue<string>(nameof(Feldname), ref fFeldname, value); }
        }
        string fBeschreibung;
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>(nameof(Beschreibung), ref fBeschreibung, value); }
        }
        HelperDatentypGenerisch fDatentypGenerisch;
        [Indexed(Name = @"iDatentypGenerisch_BDDatenbankTabelleFeld")]
        [Association(@"BDDatenbankTabelleFeldReferencesHelperDatentypGenerisch")]
        public HelperDatentypGenerisch DatentypGenerisch
        {
            get { return fDatentypGenerisch; }
            set { SetPropertyValue<HelperDatentypGenerisch>(nameof(DatentypGenerisch), ref fDatentypGenerisch, value); }
        }
        int fFeldlänge;
        public int Feldlänge
        {
            get { return fFeldlänge; }
            set { SetPropertyValue<int>(nameof(Feldlänge), ref fFeldlänge, value); }
        }
        bool fIstSchlüsselfeld;
        public bool IstSchlüsselfeld
        {
            get { return fIstSchlüsselfeld; }
            set { SetPropertyValue<bool>(nameof(IstSchlüsselfeld), ref fIstSchlüsselfeld, value); }
        }
        bool fIstPflichtfeld;
        public bool IstPflichtfeld
        {
            get { return fIstPflichtfeld; }
            set { SetPropertyValue<bool>(nameof(IstPflichtfeld), ref fIstPflichtfeld, value); }
        }
        string fFeldnamenAliase;
        public string FeldnamenAliase
        {
            get { return fFeldnamenAliase; }
            set { SetPropertyValue<string>(nameof(FeldnamenAliase), ref fFeldnamenAliase, value); }
        }
    }

}
