//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDDatenbankLibraryCRM.Database
{

    public partial class BDKundeEinzelhändler : XPLiteObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fNavisionId;
        public string NavisionId
        {
            get { return fNavisionId; }
            set { SetPropertyValue<string>(nameof(NavisionId), ref fNavisionId, value); }
        }
        string fAlteKennung;
        public string AlteKennung
        {
            get { return fAlteKennung; }
            set { SetPropertyValue<string>(nameof(AlteKennung), ref fAlteKennung, value); }
        }
        Guid fWarenwirtschaftImEinsatz;
        [Indexed(Name = @"iWarenwirtschaftImEinsatz_BDKundeEinzelhändler")]
        public Guid WarenwirtschaftImEinsatz
        {
            get { return fWarenwirtschaftImEinsatz; }
            set { SetPropertyValue<Guid>(nameof(WarenwirtschaftImEinsatz), ref fWarenwirtschaftImEinsatz, value); }
        }
        bool fWartungsvertrag;
        public bool Wartungsvertrag
        {
            get { return fWartungsvertrag; }
            set { SetPropertyValue<bool>(nameof(Wartungsvertrag), ref fWartungsvertrag, value); }
        }
        bool fKundeAktiv;
        public bool KundeAktiv
        {
            get { return fKundeAktiv; }
            set { SetPropertyValue<bool>(nameof(KundeAktiv), ref fKundeAktiv, value); }
        }
        DateTime fKundeSeit;
        public DateTime KundeSeit
        {
            get { return fKundeSeit; }
            set { SetPropertyValue<DateTime>(nameof(KundeSeit), ref fKundeSeit, value); }
        }
        bool fDSGVOVertrag;
        public bool DSGVOVertrag
        {
            get { return fDSGVOVertrag; }
            set { SetPropertyValue<bool>(nameof(DSGVOVertrag), ref fDSGVOVertrag, value); }
        }
        Guid fAnsprechpartnerBD;
        [Indexed(Name = @"iAnsprechpartnerBD_BDKundeEinzelhändler")]
        public Guid AnsprechpartnerBD
        {
            get { return fAnsprechpartnerBD; }
            set { SetPropertyValue<Guid>(nameof(AnsprechpartnerBD), ref fAnsprechpartnerBD, value); }
        }
        string fAnsprechpartnerBDAnmerkungen;
        [Size(1000)]
        public string AnsprechpartnerBDAnmerkungen
        {
            get { return fAnsprechpartnerBDAnmerkungen; }
            set { SetPropertyValue<string>(nameof(AnsprechpartnerBDAnmerkungen), ref fAnsprechpartnerBDAnmerkungen, value); }
        }
    }

}
