//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDDatenbankLibraryCRM.Database
{

    public partial class GeoAdresse : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fStraße;
        public string Straße
        {
            get { return fStraße; }
            set { SetPropertyValue<string>(nameof(Straße), ref fStraße, value); }
        }
        string fStraßeHausnummer;
        public string StraßeHausnummer
        {
            get { return fStraßeHausnummer; }
            set { SetPropertyValue<string>(nameof(StraßeHausnummer), ref fStraßeHausnummer, value); }
        }
        string fPostleitzahl;
        public string Postleitzahl
        {
            get { return fPostleitzahl; }
            set { SetPropertyValue<string>(nameof(Postleitzahl), ref fPostleitzahl, value); }
        }
        string fStadt;
        public string Stadt
        {
            get { return fStadt; }
            set { SetPropertyValue<string>(nameof(Stadt), ref fStadt, value); }
        }
        Guid fLand;
        [Indexed(Name = @"iLand_GeoAdresse")]
        public Guid Land
        {
            get { return fLand; }
            set { SetPropertyValue<Guid>(nameof(Land), ref fLand, value); }
        }
        [Association(@"BasisUnternehmenStandortReferencesGeoAdresse")]
        public XPCollection<BasisUnternehmenStandort> BasisUnternehmenStandorts { get { return GetCollection<BasisUnternehmenStandort>(nameof(BasisUnternehmenStandorts)); } }
    }

}
