//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BDDatenbankLibraryCRM.Database
{

    public partial class HelperDatentypGenerisch : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fDatentyp;
        public string Datentyp
        {
            get { return fDatentyp; }
            set { SetPropertyValue<string>(nameof(Datentyp), ref fDatentyp, value); }
        }
        string fBeschreibung;
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>(nameof(Beschreibung), ref fBeschreibung, value); }
        }
        [Association(@"BDDatenbankTabelleFeldReferencesHelperDatentypGenerisch")]
        public XPCollection<BDDatenbankTabelleFeld> BDDatenbankTabelleFelds { get { return GetCollection<BDDatenbankTabelleFeld>(nameof(BDDatenbankTabelleFelds)); } }
    }

}
